export const HoustonCarServiceActionTypes = {
    FETCH_HOUSTON_CAR_SERVICE: "FETCH_HOUSTON_CAR_SERVICE",
    FETCH_HOUSTON_CAR_SERVICE_ERROR: "FETCH_HOUSTON_CAR_SERVICE_ERROR",
    UPDATE_HOUSTON_CAR_SERVICE: "UPDATE_HOUSTON_CAR_SERVICE",
    UPDATE_HOUSTON_CAR_SERVICE_ERROR: "UPDATE_HOUSTON_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}