export const CyprusCarServiceActionTypes = {
    FETCH_CYPRUS_CAR_SERVICE: "FETCH_CYPRUS_CAR_SERVICE",
    FETCH_CYPRUS_CAR_SERVICE_ERROR: "FETCH_CYPRUS_CAR_SERVICE_ERROR",
    UPDATE_CYPRUS_CAR_SERVICE: "UPDATE_CYPRUS_CAR_SERVICE",
    UPDATE_CYPRUS_CAR_SERVICE_ERROR: "UPDATE_CYPRUS_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}