export const allBookingData = [
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 1
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 2
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 3
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 4
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 5
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 6
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 7
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 8
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 9
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Pending',
        id: 10
    },
]

// In Progress
export const inProgress = [
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 1
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 2
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 3
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 4
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 5
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 6
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 7
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 8
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 9
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'In Progress',
        id: 10
    },
]

// Completed
export const completed = [
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 1
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 2
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 3
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 4
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 5
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 6
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 7
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 8
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 9
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Completed',
        id: 10
    },
]

// Cancel
export const cancel = [
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 1
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 2
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 3
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 4
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 5
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 6
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 7
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 8
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 9
    },
    {
        name: 'Steave',
        email: 'Steave0512@ gmail.com',
        bookNumber: '10',
        bookType: 'Economy',
        carName: 'Economy',
        from: 'Airport',
        to: 'Hotel',
        date: 'Sep 22, 2020',
        time: '1:45 am',
        price: '$100',
        status: 'Cancel',
        id: 10
    },
]

// Refund
export const refund = [
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '135246',
        status: 'Details',
        id: 1
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '1234',
        status: 'Details',
        id: 2
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '16146',
        status: 'Details',
        id: 3
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '26162',
        status: 'Details',
        id: 4
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '3513',
        status: 'Details',
        id: 5
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '51',
        status: 'Details',
        id: 6
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '16',
        status: 'Details',
        id: 7
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '14',
        status: 'Details',
        id: 8
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '13',
        status: 'Details',
        id: 9
    },
    {
        name: 'Steave',
        email: '411',
        bookNumber: '319',
        carName: '12',
        status: 'Details',
        id: 10
    },
]