export const HoustonToVictoriaActionTypes = {
    FETCH_HOUSTON_TO_Victoria: "FETCH_HOUSTON_TO_Victoria",
    FETCH_HOUSTON_TO_Victoria_ERROR: "FETCH_HOUSTON_TO_Victoria_ERROR",
    UPDATE_HOUSTON_TO_Victoria: "UPDATE_HOUSTON_TO_Victoria",
    UPDATE_HOUSTON_TO_Victoria_ERROR: "UPDATE_HOUSTON_TO_Victoria_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES"
}