export const KatyCarServiceActionTypes = {
    FETCH_KATY_CAR_SERVICE: "FETCH_KATY_CAR_SERVICE",
    FETCH_KATY_CAR_SERVICE_ERROR: "FETCH_KATY_CAR_SERVICE_ERROR",
    UPDATE_KATY_CAR_SERVICE: "UPDATE_KATY_CAR_SERVICE",
    UPDATE_KATY_CAR_SERVICE_ERROR: "UPDATE_KATY_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}