export const HoustonToLafayetteActionTypes = {
    FETCH_HOUSTON_TO_LAFAYETTE: "FETCH_HOUSTON_TO_LAFAYETTE",
    FETCH_HOUSTON_TO_LAFAYETTE_ERROR: "FETCH_HOUSTON_TO_LAFAYETTE_ERROR",
    UPDATE_HOUSTON_TO_LAFAYETTE: "UPDATE_HOUSTON_TO_LAFAYETTE",
    UPDATE_HOUSTON_TO_LAFAYETTE_ERROR: "UPDATE_HOUSTON_TO_LAFAYETTE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}