export const HoustonToDallasActionTypes = {
    FETCH_HOUSTON_TO_DALLAS: "FETCH_HOUSTON_TO_DALLAS",
    FETCH_HOUSTON_TO_DALLAS_ERROR: "FETCH_HOUSTON_TO_DALLAS_ERROR",
    UPDATE_HOUSTON_TO_DALLAS: "UPDATE_HOUSTON_TO_DALLAS",
    UPDATE_HOUSTON_TO_DALLAS_ERROR: "UPDATE_HOUSTON_TO_DALLAS_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}