export const CitiesActionTypes = {
    FETCH_CITIES: "FETCH_CITIES",
    FETCH_CITIES_ERROR: "FETCH_CITIES_ERROR",
    DELETE_CITY_REQUEST: "DELETE_CITY_REQUEST",
    DELETE_CITY: "DELETE_CITY",
    DELETE_CITY_ERROR: "DELETE_CITY_ERROR",
    ADD_CITY: "ADD_CITY",
    ADD_CITY_ERROR: "ADD_CITY_ERROR",
    CLEAR_MESSAGE: "CLEAR_MESSAGE"
}