export const ConroeCarServiceActionTypes = {
    FETCH_CONROE_CAR_SERVICE: "FETCH_CONROE_CAR_SERVICE",
    FETCH_CONROE_CAR_SERVICE_ERROR: "FETCH_CONROE_CAR_SERVICE_ERROR",
    UPDATE_CONROE_CAR_SERVICE: "UPDATE_CONROE_CAR_SERVICE",
    UPDATE_CONROE_CAR_SERVICE_ERROR: "UPDATE_CONROE_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}