export const HoustonToSantonioActionTypes = {
    FETCH_HOUSTON_TO_SANTONIO: "FETCH_HOUSTON_TO_SANTONIO",
    FETCH_HOUSTON_TO_SANTONIO_ERROR: "FETCH_HOUSTON_TO_SANTONIO_ERROR",
    UPDATE_HOUSTON_TO_SANTONIO: "UPDATE_HOUSTON_TO_SANTONIO",
    UPDATE_HOUSTON_TO_SANTONIO_ERROR: "UPDATE_HOUSTON_TO_SANTONIO_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}