export const BusinessConventionActionTypes = {
    FETCH_BUSINESS_CONVENTION: "FETCH_BUSINESS_CONVENTION",
    FETCH_BUSINESS_CONVENTION_ERROR: "FETCH_BUSINESS_CONVENTION_ERROR",
    UPDATE_BUSINESS_CONVENTION: "UPDATE_BUSINESS_CONVENTION",
    UPDATE_BUSINESS_CONVENTION_ERROR: "UPDATE_BUSINESS_CONVENTION_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}