export const AboutActionTypes = {
    FETCH_ABOUT: "FETCH_ABOUT",
    FETCH_ABOUT_ERROR: "FETCH_ABOUT_ERROR",
    UPDATE_ABOUT: "UPDATE_ABOUT",
    UPDATE_ABOUT_ERROR: "UPDATE_ABOUT_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES"
}