export const TombaliCarServiceActionTypes = {
    FETCH_TOMBALI_CAR_SERVICE: "FETCH_TOMBALI_CAR_SERVICE",
    FETCH_TOMBALI_CAR_SERVICE_ERROR: "FETCH_TOMBALI_CAR_SERVICE_ERROR",
    UPDATE_TOMBALI_CAR_SERVICE: "UPDATE_TOMBALI_CAR_SERVICE",
    UPDATE_TOMBALI_CAR_SERVICE_ERROR: "UPDATE_TOMBALI_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}