export const ConcertsTheatresActionTypes = {
    FETCH_CONCERTS_THEATRES: "FETCH_CONCERTS_THEATRES",
    FETCH_CONCERTS_THEATRES_ERROR: "FETCH_CONCERTS_THEATRES_ERROR",
    UPDATE_CONCERTS_THEATRES: "UPDATE_CONCERTS_THEATRES",
    UPDATE_CONCERTS_THEATRES_ERROR: "UPDATE_CONCERTS_THEATRES_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}