export const HoustonHobbyActionTypes = {
    FETCH_HOUSTON_HOBBY: "FETCH_HOUSTON_HOBBY",
    FETCH_HOUSTON_HOBBY_ERROR: "FETCH_HOUSTON_HOBBY_ERROR",
    UPDATE_HOUSTON_HOBBY: "UPDATE_HOUSTON_HOBBY",
    UPDATE_HOUSTON_HOBBY_ERROR: "UPDATE_HOUSTON_HOBBY_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}