export const MeetCrewActionTypes = {
    FETCH_MEET_CREW: "FETCH_MEET_CREW",
    FETCH_MEET_CREW_ERROR: "FETCH_MEET_CREW_ERROR",
    DELETE_CREW: "DELETE_CREW",
    DELETE_CREW_ERROR: "DELETE_CREW_ERROR",
    ADD_CREW: "ADD_CREW",
    ADD_CREW_ERROR: "ADD_CREW_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}