export const GeorgeBushActionTypes = {
    FETCH_GEORGE_BUSH: "FETCH_GEORGE_BUSH",
    FETCH_GEORGE_BUSH_ERROR: "FETCH_GEORGE_BUSH_ERROR",
    UPDATE_GEORGE_BUSH: "UPDATE_GEORGE_BUSH",
    UPDATE_GEORGE_BUSH_ERROR: "UPDATE_GEORGE_BUSH_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}