export const PrivateJetActionTypes = {
    FETCH_PRIVATE_JET: "FETCH_PRIVATE_JET",
    FETCH_PRIVATE_JET_ERROR: "FETCH_PRIVATE_JET_ERROR",
    UPDATE_PRIVATE_JET: "UPDATE_PRIVATE_JET",
    UPDATE_PRIVATE_JET_ERROR: "UPDATE_PRIVATE_JET_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES"
}