export const BachelorPartyActionTypes = {
    FETCH_BACHELOR_PARTY: "FETCH_BACHELOR_PARTY",
    FETCH_BACHELOR_PARTY_ERROR: "FETCH_BACHELOR_PARTY_ERROR",
    UPDATE_BACHELOR_PARTY: "UPDATE_BACHELOR_PARTY",
    UPDATE_BACHELOR_PARTY_ERROR: "UPDATE_BACHELOR_PARTY_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}