export const RichmondCarServiceActionTypes = {
    FETCH_RICHMOND_CAR_SERVICE: "FETCH_RICHMOND_CAR_SERVICE",
    FETCH_RICHMOND_CAR_SERVICE_ERROR: "FETCH_RICHMOND_CAR_SERVICE_ERROR",
    UPDATE_RICHMOND_CAR_SERVICE: "UPDATE_RICHMOND_CAR_SERVICE",
    UPDATE_RICHMOND_CAR_SERVICE_ERROR: "UPDATE_RICHMOND_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}