export const SpringCarServiceActionTypes = {
    FETCH_Spring_CAR_SERVICE: "FETCH_Spring_CAR_SERVICE",
    FETCH_Spring_CAR_SERVICE_ERROR: "FETCH_Spring_CAR_SERVICE_ERROR",
    UPDATE_Spring_CAR_SERVICE: "UPDATE_Spring_CAR_SERVICE",
    UPDATE_Spring_CAR_SERVICE_ERROR: "UPDATE_Spring_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}