export const BeamountCarServiceActionTypes = {
    FETCH_BEAMOUNT_CAR_SERVICE: "FETCH_BEAMOUNT_CAR_SERVICE",
    FETCH_BEAMOUNT_CAR_SERVICE_ERROR: "FETCH_BEAMOUNT_CAR_SERVICE_ERROR",
    UPDATE_BEAMOUNT_CAR_SERVICE: "UPDATE_BEAMOUNT_CAR_SERVICE",
    UPDATE_BEAMOUNT_CAR_SERVICE_ERROR: "UPDATE_BEAMOUNT_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}