export const HoustonToCollegeActionTypes = {
    FETCH_HOUSTON_TO_COLLEGE: "FETCH_HOUSTON_TO_COLLEGE",
    FETCH_HOUSTON_TO_COLLEGE_ERROR: "FETCH_HOUSTON_TO_COLLEGE_ERROR",
    UPDATE_HOUSTON_TO_COLLEGE: "UPDATE_HOUSTON_TO_COLLEGE",
    UPDATE_HOUSTON_TO_COLLEGE_ERROR: "UPDATE_HOUSTON_TO_COLLEGE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES"
}