export const BachelorettePartyActionTypes = {
  FETCH_BACHELORETTE_PARTY: "FETCH_BACHELORETTE_PARTY",
  FETCH_BACHELORETTE_PARTY_ERROR: "FETCH_BACHELORETTE_PARTY_ERROR",
  UPDATE_BACHELORETTE_PARTY: "UPDATE_BACHELORETTE_PARTY",
  UPDATE_BACHELORETTE_PARTY_ERROR: "UPDATE_BACHELORETTE_PARTY_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
};
