export const AstroActionTypes = {
    FETCH_ASTRO: "FETCH_ASTRO",
    FETCH_ASTRO_ERROR: "FETCH_ASTRO_ERROR",
    UPDATE_ASTRO: "UPDATE_ASTRO",
    UPDATE_ASTRO_ERROR: "UPDATE_ASTRO_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES"
}