export const UpdateContactDetailsActionTypes = {
    UPDATE_CONTACT_DETAILS_LOADING: "UPDATE_CONTACT_DETAILS_LOADING",
    UPDATE_CONTACT_DETAILS: "UPDATE_CONTACT_DETAILS",
    UPDATE_CONTACT_DETAILS_SUCCESS: "UPDATE_CONTACT_DETAILS_SUCCESS",
}