export const GalvestonActionTypes = {
    FETCH_GALVESTON: "FETCH_GALVESTON",
    FETCH_GALVESTON_ERROR: "FETCH_GALVESTON_ERROR",
    UPDATE_GALVESTON: "UPDATE_GALVESTON",
    UPDATE_GALVESTON_ERROR: "UPDATE_GALVESTON_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_MESSAGES: "CLEAR_MESSAGES"
}