export const FETCH_REFUND_REQUEST = "FETCH_REFUND_REQUEST";
export const FETCH_REFUND_REQUEST_ERROR = "FETCH_REFUND_REQUEST_ERROR";

export const REFUND_REQUEST_DETAILS_LOADING = "REFUND_REQUEST_DETAILS_LOADING";
export const REFUND_REQUEST_DETAILS_SUCCESS = "REFUND_REQUEST_DETAILS_SUCCESS";
export const REFUND_REQUEST_DETAILS_ERROR = "REFUND_REQUEST_DETAILS_ERROR";
