export const GalvestonCarServiceActionTypes = {
    FETCH_GALVESTON_CAR_SERVICE: "FETCH_GALVESTON_CAR_SERVICE",
    FETCH_GALVESTON_CAR_SERVICE_ERROR: "FETCH_GALVESTON_CAR_SERVICE_ERROR",
    UPDATE_GALVESTON_CAR_SERVICE: "UPDATE_GALVESTON_CAR_SERVICE",
    UPDATE_GALVESTON_CAR_SERVICE_ERROR: "UPDATE_GALVESTON_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}