export const PromLimoActionTypes = {
  FETCH_PROM_LIMO: "FETCH_PROM_LIMO",
  FETCH_PROM_LIMO_ERROR: "FETCH_PROM_LIMO_ERROR",
  UPDATE_PROM_LIMO: "UPDATE_PROM_LIMO",
  UPDATE_PROM_LIMO_ERROR: "UPDATE_PROM_LIMO_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
};
