export const ContactUsActionTypes = {
    FETCH_CONTACT_US_LOADING: "FETCH_CONTACT_US_LOADING",
    FETCH_CONTACT_US: "FETCH_CONTACT_US",
    FETCH_CONTACT_US_ERROR: "FETCH_CONTACT_US_ERROR",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    DELETE_MESSAGE_LOADING: "DELETE_MESSAGE_LOADING",
}