export const NewsActionTypes = {
    FETCH_NEWS: "FETCH_NEWS",
    FETCH_NEWS_ERROR: "FETCH_NEWS_ERROR",
    DELETE_NEWS: "DELETE_NEWS",
    DELETE_NEWS_ERROR: "DELETE_NEWS_ERROR",
    ADD_NEWS: "ADD_NEWS",
    ADD_NEWS_ERROR: "ADD_NEWS_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_MESSAGE: "CLEAR_MESSAGE"
}