export const HoustonToLakecharlesActionTypes = {
    FETCH_HOUSTON_TO_LAKECHARLES: "FETCH_HOUSTON_TO_LAKECHARLES",
    FETCH_HOUSTON_TO_LAKECHARLES_ERROR: "FETCH_HOUSTON_TO_LAKECHARLES_ERROR",
    UPDATE_HOUSTON_TO_LAKECHARLES: "UPDATE_HOUSTON_TO_LAKECHARLES",
    UPDATE_HOUSTON_TO_LAKECHARLES_ERROR: "UPDATE_HOUSTON_TO_LAKECHARLES_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}