export const UsersActionTypes = {
    FETCH_ALL_USERS: "FETCH_ALL_USERS",
    FETCH_ALL_USERS_ERROR: "FETCH_ALL_USERS_ERROR",
    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    DELETE_USER: "DELETE_USER",
    DELETE_USER_ERROR: "DELETE_USER_ERROR",
    CLEAR_MESSAGE: "CLEAR_MESSAGE"
}