export const MontgomeryCarServiceActionTypes = {
    FETCH_MONTGOMERY_CAR_SERVICE: "FETCH_MONTGOMERY_CAR_SERVICE",
    FETCH_MONTGOMERY_CAR_SERVICE_ERROR: "FETCH_MONTGOMERY_CAR_SERVICE_ERROR",
    UPDATE_MONTGOMERY_CAR_SERVICE: "UPDATE_MONTGOMERY_CAR_SERVICE",
    UPDATE_MONTGOMERY_CAR_SERVICE_ERROR: "UPDATE_MONTGOMERY_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}