export const PartyActionTypes = {
    FETCH_PARTY: "FETCH_PARTY",
    FETCH_PARTY_ERROR: "FETCH_PARTY_ERROR",
    UPDATE_PARTY: "UPDATE_PARTY",
    UPDATE_PARTY_ERROR: "UPDATE_PARTY_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}