export const HoustonToAustinActionTypes = {
    FETCH_HOUSTON_TO_AUSTIN: "FETCH_HOUSTON_TO_AUSTIN",
    FETCH_HOUSTON_TO_AUSTIN_ERROR: "FETCH_HOUSTON_TO_AUSTIN_ERROR",
    UPDATE_HOUSTON_TO_AUSTIN: "UPDATE_HOUSTON_TO_AUSTIN",
    UPDATE_HOUSTON_TO_AUSTIN_ERROR: "UPDATE_HOUSTON_TO_AUSTIN_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}