export const HoustonRadeoActionTypes = {
    FETCH_HOUSTON_RADEO: "FETCH_HOUSTON_RADEO",
    FETCH_HOUSTON_RADEO_ERROR: "FETCH_HOUSTON_RADEO_ERROR",
    UPDATE_HOUSTON_RADEO: "UPDATE_HOUSTON_RADEO",
    UPDATE_HOUSTON_RADEO_ERROR: "UPDATE_HOUSTON_RADEO_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}