export const ContactDetailsActionTypes = {
    FETCH_CONTACT_DETAILS: "FETCH_CONTACT_DETAILS_LOADING",
    FETCH_CONTACT_DETAILS_ERROR: "FETCH_CONTACT_DETAILS_ERROR",
    UPDATE_CONTACT_DETAILS: "UPDATE_CONTACT_DETAILS_LOADING",
    UPDATE_CONTACT_DETAILS_ERROR: "UPDATE_CONTACT_DETAILS",
    CLEAR_MESSAGE: "CLEAR_MESSAGE"
}