export const GraduationTransferActionTypes = {
    FETCH_GRADUATION_TRANSFER: "FETCH_GRADUATION_TRANSFER",
    FETCH_GRADUATION_TRANSFER_ERROR: "FETCH_GRADUATION_TRANSFER_ERROR",
    UPDATE_GRADUATION_TRANSFER: "UPDATE_GRADUATION_TRANSFER",
    UPDATE_GRADUATION_TRANSFER_ERROR: "UPDATE_GRADUATION_TRANSFER_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}