export const SugarlandCarServiceActionTypes = {
    FETCH_SUGARLAND_CAR_SERVICE: "FETCH_SUGARLAND_CAR_SERVICE",
    FETCH_SUGARLAND_CAR_SERVICE_ERROR: "FETCH_SUGARLAND_CAR_SERVICE_ERROR",
    UPDATE_SUGARLAND_CAR_SERVICE: "UPDATE_SUGARLAND_CAR_SERVICE",
    UPDATE_SUGARLAND_CAR_SERVICE_ERROR: "UPDATE_SUGARLAND_CAR_SERVICE_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR"
}